var mongoose = require('mongoose');

var schema = module.exports = new mongoose.Schema({
  "id": Number,
  "listing_url": String,
  "scrape_id": Number,
  "last_scraped": String,
  "name": String,
  "summary": String,
  "space": String,
  "description": String,
  "experiences_offered": String,
  "neighborhood_overview": String,
  "notes": String,
  "transit": String,
  "thumbnail_url": String,
  "medium_url": String,
  "picture_url": String,
  "xl_picture_url": String,
  "host_id": Number,
  "host_url": String,
  "host_name": String,
  "host_since": String,
  "host_location": String,
  "host_about": String,
  "host_response_time": String,
  "host_response_rate": String,
  "host_acceptance_rate": String,
  "host_is_superhost": String,
  "host_thumbnail_url": String,
  "host_picture_url": String,
  "host_neighbourhood": String,
  "host_listings_count": Number,
  "host_total_listings_count": Number,
  "host_verifications": String,
  "host_has_profile_pic": String,
  "host_identity_verified": String,
  "street": String,
  "neighbourhood": String,
  "neighbourhood_cleansed": String,
  "neighbourhood_group_cleansed": String,
  "city": String,
  "state": String,
  "zipcode": Number,
  "market": String,
  "smart_location": String,
  "country_code": String,
  "country": String,
  "latitude": Number,
  "longitude": Number,
  "is_location_exact": String,
  "property_type": String,
  "room_type": String,
  "accommodates": Number,
  "bathrooms": Number,
  "bedrooms": Number,
  "beds": Number,
  "bed_type": String,
  "amenities": String,
  "square_feet": String,
  "price": String,
  "weekly_price": String,
  "monthly_price": String,
  "security_deposit": String,
  "cleaning_fee": String,
  "guests_included": Number,
  "extra_people": String,
  "minimum_nights": Number,
  "maximum_nights": Number,
  "calendar_updated": String,
  "has_availability": String,
  "availability_30": Number,
  "availability_60": Number,
  "availability_90": Number,
  "availability_365": Number,
  "calendar_last_scraped": String,
  "number_of_reviews": Number,
  "first_review": String,
  "last_review": String,
  "review_scores_rating": String,
  "review_scores_accuracy": String,
  "review_scores_cleanliness": String,
  "review_scores_checkin": String,
  "review_scores_communication": String,
  "review_scores_location": String,
  "review_scores_value": String,
  "requires_license": String,
  "license": String,
  "jurisdiction_names": String,
  "instant_bookable": String,
  "cancellation_policy": String,
  "require_guest_profile_picture": String,
  "require_guest_phone_verification": String,
  "calculated_host_listings_count": Number,
  "reviews_per_month": String
});

schema.index({
  market: 1
}, {name: 'marketIndex'});


schema.pre('save', function(next) {
  next();
});

if (!schema.options.toJSON) schema.options.toJSON = {};
schema.options.toJSON.transform = function (doc, ret) {
  ret.id = ret._id;
  delete ret._id;
};